DROP TABLE IF EXISTS "weigth";
DROP TABLE IF EXISTS "consumptiondetail";
DROP TABLE IF EXISTS "consumption";
DROP TABLE IF EXISTS "recipe_product_link";
DROP TABLE IF EXISTS "favoriteproduct";
DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "productcategory";
DROP TABLE IF EXISTS "unit";
DROP TABLE IF EXISTS "users";
